window.employeeData = [
  {
    id: 1,
    firstName: "Mukesh",
    lastName: "Kumar",
    email: "mukesh@example.com",
    department: "Engineering",
    role: "Developer",
  },
  {
    id: 2,
    firstName: "Anita",
    lastName: "Sharma",
    email: "anita@example.com",
    department: "HR",
    role: "Manager",
  },
  {
    id: 3,
    firstName: "Raj",
    lastName: "Verma",
    email: "raj@example.com",
    department: "Design",
    role: "Designer",
  },
  {
    id: 4,
    firstName: "Neha",
    lastName: "Singh",
    email: "neha@example.com",
    department: "Marketing",
    role: "Marketing",
  },
  {
    id: 5,
    firstName: "Amit",
    lastName: "Yadav",
    email: "amit@example.com",
    department: "Sales",
    role: "Sales",
  },
  {
    id: 6,
    firstName: "Priya",
    lastName: "Rao",
    email: "priya@example.com",
    department: "Engineering",
    role: "Developer",
  },
  {
    id: 7,
    firstName: "Karan",
    lastName: "Mehta",
    email: "karan@example.com",
    department: "Design",
    role: "Designer",
  },
  {
    id: 8,
    firstName: "Sunita",
    lastName: "Mishra",
    email: "sunita@example.com",
    department: "Marketing",
    role: "Marketing",
  },
  {
    id: 9,
    firstName: "Divya",
    lastName: "Kapoor",
    email: "divya@example.com",
    department: "Engineering",
    role: "Developer",
  },
  {
    id: 10,
    firstName: "Arjun",
    lastName: "Gupta",
    email: "arjun@example.com",
    department: "Design",
    role: "Designer",
  },
  {
    id: 11,
    firstName: "Meena",
    lastName: "Nair",
    email: "meena@example.com",
    department: "Marketing",
    role: "Marketing",
  },
  {
    id: 12,
    firstName: "Sneha",
    lastName: "Joshi",
    email: "sneha@example.com",
    department: "Engineering",
    role: "Developer",
  },
  {
    id: 13,
    firstName: "Alok",
    lastName: "Singh",
    email: "alok@example.com",
    department: "Engineering",
    role: "Developer",
  },
  {
    id: 14,
    firstName: "Gaurav",
    lastName: "Reddy",
    email: "gaurav@example.com",
    department: "Engineering",
    role: "Developer",
  },
  {
    id: 15,
    firstName: "Bhavna",
    lastName: "Shukla",
    email: "bhavna@example.com",
    department: "Sales",
    role: "Sales",
  },
  {
    id: 16,
    firstName: "Komal",
    lastName: "Pathak",
    email: "komal@example.com",
    department: "Sales",
    role: "Sales",
  },
  {
    id: 17,
    firstName: "Jaya",
    lastName: "Kulkarni",
    email: "jaya@example.com",
    department: "Sales",
    role: "Sales",
  },
  {
    id: 18,
    firstName: "Lavanya",
    lastName: "Rawat",
    email: "lavanya@example.com",
    department: "Sales",
    role: "Sales",
  },
  {
    id: 19,
    firstName: "Meher",
    lastName: "Sheikh",
    email: "meher@example.com",
    department: "Design",
    role: "Designer",
  },
  {
    id: 20,
    firstName: "Zara",
    lastName: "Iqbal",
    email: "zara@example.com",
    department: "Marketing",
    role: "Marketing",
  },
  {
    id: 21,
    firstName: "Ishaan",
    lastName: "Chandra",
    email: "ishaan@example.com",
    department: "Sales",
    role: "Sales",
  },
  {
    id: 22,
    firstName: "Sanya",
    lastName: "Paul",
    email: "sanya@example.com",
    department: "Design",
    role: "Designer",
  },
];
